const ActionType = {
    COMPANY: "COMPANY",
    CATEGORY: "CATEGORY",
    PRODUCTS: "PRODUCTS",
    COUPONS: "COUPONS",
    CONFIRMATIONDIALOG: "CONFIRMATIONDIALOG",
    OFFERDISCOUNT: "OFFERDISCOUNT",
    DIALOG: "DIALOG",
    USER:"USER",
    TOKEN:"TOKEN",
    BLOGS:"BLOGS",
    ORDERS:"ORDERS",
    ORDER:"ORDER"
}

export default ActionType;